### PR TITLE
 compliance in rtn-082

### PR DESCRIPTION
**Pull request by womullan**

### CODE REVIEW

**Comment by jhoblitt** [comment]
typo in the PR title.

**Comment by jhoblitt** [comment]
The same typo is in a commit message.

**Review by drphilmarshall — COMMENTED** [review]
So you want to separate the plan for meeting the data security standards (this doc) from the report on how well we are doing at that (RTN-082)? I think that makes sense, but I'll need to explain and justify the change to Helmut and Ashley. How would you put it to them? I'll merge this PR and send them a new PDF once I have transmitted that explanation.

**Comment by womullan** [comment]
This appendix was a first estimate of compliance. We will now have a Pixel Zone Security Plan and an Embargo Security plan so its out of date and no longer covering all Rubin. It is also against 800.171r2 while we now have r3.. The table was a level too deep for that document and indeed should change as we progress - having that in a heavily change controlled document was not a great idea.

**Review by drphilmarshall — APPROVED** [review]
Helmut concurs this change is a good idea.

**Pull request merged**
